package client.gui;

import client.MainClient;
import client.ProxyClient;
import javafx.animation.PauseTransition;
import javafx.animation.RotateTransition;
import javafx.animation.SequentialTransition;
import javafx.animation.TranslateTransition;
import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.ImageView;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import javafx.util.Duration;
import shared.Logger;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;

/**
    This class is the controller associated with {@code WaitingRoom.fxml}. It shows a simple animation and gives the user the opportunity for disconnecting.
    Once the loading has been completed the {@code chooseWindow(...)} method is called from {@link ProxyClient#chooseWindow(ArrayList, ArrayList)}.
    {@code chooseWindow(...)} saves the 4 cards to be chosen by the user in {@link MainClient#chosenCards} and then, once the cards have been saved,
    it loads the next view and the {@link ChooseWindowController}.
 */

public class WaitingRoomController implements Initializable {

    @FXML
    private AnchorPane paneBackground;
    @FXML
    private ImageView outerCircle;
    @FXML
    private ImageView bar1,bar2,bar3,bar4,bar5;

    private ArrayList<ImageView> bars = new ArrayList<>();
    private ProxyClient proxyClient = ProxyClient.getInstance();




    public WaitingRoomController() {
        MainClient.setWaitingRoomController(this);
    }


    /**
     Initialize with transition and loads the array containing the imageViews of the bars
     */
    public void initialize(URL location, ResourceBundle resources) {
        loadArray();
        rotateTransition();
        int wait=0;
        for(int i=0; i<bars.size();i++){
            barTransitions(wait, bars.get(i));
            wait=wait+100;


        }


    }
    /**
     Method called by {@link ProxyClient} in order to load the view with the selection of cards. It saves the {@param listCard} in {@link MainClient#chosenCards} in order
     to make them available to the {@link ChooseWindowController} class. This because once the new view has been loaded, the current controller will not be accessible anymore.
     */
    public void chooseWindow(ArrayList<Integer> listCard) {

        Platform.runLater(
                () -> {
                    
                    MainClient.setChosenCards(listCard);

                    // Loading of ChooseWindow view, where you can choose your own map
                    FXMLLoader loader = new FXMLLoader(getClass().getResource("/ChooseWindow.fxml"));
                    try {
                        Parent root1 = loader.load();
                        Scene startedGame = new Scene(root1, 1280, 800, Color.WHITE);
                        Stage window = (Stage) paneBackground.getScene().getWindow();
                        window.setScene(startedGame);
                        window.show();
                    } catch (IOException Exception) {
                        Logger.log("View not found. Error while loading");

                    }
                }
        );


    }
    private  void loadArray(){
        bars.add(bar1);
        bars.add(bar2);
        bars.add(bar3);
        bars.add(bar4);
        bars.add(bar5);

    }
    private void rotateTransition(){
        RotateTransition rt = new RotateTransition(Duration.millis(3000),outerCircle );
        rt.setByAngle(360);
        rt.setCycleCount(100);
        rt.play();
    }

    private void barTransitions(int attesa, ImageView bar ){
        PauseTransition pt = new PauseTransition(Duration.millis(attesa));
        TranslateTransition tt = new TranslateTransition(Duration.seconds(1));
        tt.setNode(bar);
        tt.setByY(50);
        tt.setAutoReverse(true);
        tt.setCycleCount(100);
        SequentialTransition seqT = new SequentialTransition (bar, pt, tt);
        seqT.play();

    }
    /**
        Clicking the {@code disconnectButton} in {@code WaitingRoom.fxml } will call {@link ProxyClient#exitGame1()} and it disconnects the player.
        Once the player is disconnected, he's routed back to the Login view generated by {@link LogInScreenController}.
      */
    @FXML
    private void disconnect(ActionEvent event){
        proxyClient.exitGame1();

        FXMLLoader loader = new FXMLLoader(getClass().getResource("/LogInScreen.fxml"));
        try {
            Parent root1 = loader.load();
            Scene startedGame = new Scene(root1, 1280, 800, Color.WHITE);
            Stage window = (Stage) paneBackground.getScene().getWindow();
            window.setScene(startedGame);
            window.show();
        } catch (IOException Exception) {
            Logger.log("View not found. Error while loading");

        }





    }

}